/*
 * CriteriaView.java
 *
 * Created on April 30, 2011, 9:05 AM
 */

package com.purediscovery.vennlayout.ui;

import com.purediscovery.vennlayout.model.SetCriteria;

/**
 *
 * @author  home
 */
public class CriteriaView extends javax.swing.JPanel {
    private SetCriteria setCriteria;

    /** Creates new form CriteriaView */
    public CriteriaView() {
        initComponents();
    }


    public CriteriaView(SetCriteria setCriteria) {
        this();
        this.setCriteria = setCriteria;
        nameLabel.setText(setCriteria.getName());
        load();
    }

    private void load() {
        valueTextField.setText(Double.toString(setCriteria.getGoalArea()));
    }

    private void save() {
        setCriteria.setGoalArea(Double.parseDouble(valueTextField.getText()));
        load();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 30));
        setDoubleBuffered(false);
        setLayout(new java.awt.BorderLayout(10, 0));

        nameLabel.setText("Name");
        add(nameLabel, java.awt.BorderLayout.CENTER);

        valueTextField.setText("Value");
        valueTextField.setInheritsPopupMenu(true);
        valueTextField.setPreferredSize(new java.awt.Dimension(100, 28));
        valueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextFieldActionPerformed(evt);
            }
        });
        valueTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valueTextFieldFocusLost(evt);
            }
        });
        add(valueTextField, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void valueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextFieldActionPerformed
        save();
    }//GEN-LAST:event_valueTextFieldActionPerformed

    private void valueTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valueTextFieldFocusLost
        save();
    }//GEN-LAST:event_valueTextFieldFocusLost
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
    
}
