/*
 * Controls.java
 *
 * Created on April 30, 2011, 8:51 AM
 */

package com.purediscovery.vennlayout.ui;

import com.purediscovery.vennlayout.model.GALayout;
import com.purediscovery.vennlayout.model.SetCriteria;
import com.purediscovery.vennlayout.model.SetLayout;
import com.purediscovery.vennlayout.model.VennException;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author home
 */
public class MainView extends javax.swing.JPanel {
    private GALayout gaLayout;
    private RenderPanel renderPanel;
    private SetLayout selectedSetLayout = null;
    private Timer timer;

    /**
     * Creates new form Controls
     */
    public MainView() {
        initComponents();
    }

    public MainView(GALayout gaLayout) {
        this();
        this.gaLayout = gaLayout;
        renderPanel = new RenderPanel(gaLayout);
        centerPanel.add(renderPanel);

        loadControls();
        rebuildPopulationList();
        initListListener();

        revalidate();
    }

    private void initListListener() {
        populationList.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                int index = populationList.getSelectedIndex();
                if (index != -1)
                    selectedSetLayout = gaLayout.getPopulation().get(index);
            }
        });
    }

    private void rebuildPopulationList() {
        Object o = populationList.getSelectedValue();

        DefaultListModel m = new DefaultListModel();

        synchronized (gaLayout.getPopulation()) {
            for (SetLayout layout : gaLayout.getPopulation())
                m.addElement(layout);
        }
        populationList.setModel(m);

        if (o != null) {
            populationList.setSelectedValue(o, true);
        }
    }


    private void loadControls() {
        for (SetCriteria setCriteria : gaLayout.getSetCriteriaList()) {
            controlsListPanel.add(new CriteriaView(setCriteria));
        }

        this.revalidate();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generationLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        startStopToggleButton = new javax.swing.JToggleButton();
        controlScrollPane = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        controlsListPanel = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        populationList = new javax.swing.JList();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        generationLabel.setText("0");
        generationLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(generationLabel, java.awt.BorderLayout.SOUTH);

        startStopToggleButton.setText("Start");
        startStopToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopToggleButtonActionPerformed(evt);
            }
        });
        jPanel3.add(startStopToggleButton);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        controlScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        controlsListPanel.setLayout(new java.awt.GridLayout(0, 1));
        jPanel2.add(controlsListPanel, java.awt.BorderLayout.NORTH);

        controlScrollPane.setViewportView(jPanel2);

        jPanel1.add(controlScrollPane, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.WEST);

        centerPanel.setLayout(new java.awt.BorderLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(populationList);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.EAST);

        add(jPanel4, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void startStopToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopToggleButtonActionPerformed

        if (gaLayout.isRunning())
            stop();
        else
            start();

        updateRunButton();

    }//GEN-LAST:event_startStopToggleButtonActionPerformed

    private void updateRunButton() {
        startStopToggleButton.setText(gaLayout.isRunning() ? "Stop" : "Start");
        startStopToggleButton.setSelected(gaLayout.isRunning());
    }


    private void start() {
        if (gaLayout.isRunning())
            gaLayout.stop();

        timer = new Timer(500, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                update();
            }
        });
        timer.start();

        gaLayout.start();

    }

    private void stop() {

        gaLayout.stop();
    }

    private void update() {
        System.out.println("update.");

        generationLabel.setText(Integer.toString(gaLayout.getGenerationCount()));
        rebuildPopulationList();
        repaint();

        if (!gaLayout.isRunning()) {
            timer.stop();
        }
        updateRunButton();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane controlScrollPane;
    private javax.swing.JPanel controlsListPanel;
    private javax.swing.JLabel generationLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList populationList;
    private javax.swing.JToggleButton startStopToggleButton;
    // End of variables declaration//GEN-END:variables

}
